microsoft/vscode-azurecontainerapps

package-lock.json, package.json, package.nls.json, src/commands/createKubeEnvironment/KubeEnvironmentCreateStep.ts, src/commands/createKubeEnvironment/LogAnalyticsCreateStep.ts, src/commands/createKubeEnvironment/LogAnalyticsListStep.ts, src/commands/createKubeEnvironment/createKubeEnvironment.ts, src/commands/deployImage/acr/AcrRepositoriesListStep.ts, src/commands/deployImage/acr/AcrTagListStep.ts, src/commands/openInPortal.ts, src/commands/registerCommands.ts, src/commands/revisionCommands/changeRevisionActiveState.ts, src/tree/ContainerAppTreeItem.ts, src/tree/KubeEnvironmentTreeItem.ts, src/tree/SubscriptionTreeItem.ts, src/utils/azureClients.ts, src/utils/settingUtils.ts, webpack.config.js
PR ended up getting a bit away from me, but will break it down below
---
This PR depends on the following PRs:
- https://github.com/microsoft/vscode-azure-account/commit/d4ec3d8e1e7dec16a03e1cb361b4e1d4f09a7a28
- https://github.com/microsoft/vscode-azuretools/commit/d3b4e61a34908d8226b20d45881b48427e2cdd91
Because the Container Apps sdk is T2, I had to upgrade the credential types in order to use it.  Previously, I was getting around this using the `azure-identity` package, but this brought in a dependency on `keytar` which ended up breaking the vsix on Mac/Linux.  The changes related to getting ride of the `VisualStudioCodeCredentials` such as https://github.com/microsoft/vscode-azurecontainerapps/compare/nat/delete?expand=1#diff-17e919c422cbcd1b90fea9dac31ba7001932c46adae157768f07a1bf5cd …
=> Delete KubeEnvironments + other things

main.js, package-lock.json, package.json, package.nls.json, src/commands/chooseRevisionMode.ts, src/commands/deployImage/deployImage.ts, src/tree/ContainerAppTreeItem.ts, src/tree/DaprTreeItem.ts, src/utils/azureClients.ts
Fixes https://github.com/microsoft/vscode-azurecontainerapps/issues/47
If the Container App is in single revision mode, the revision tree item shouldn't be displayed because it's just confusing.  Based on whether or not it's enabled, where the user can swap RevisionMode context action exists on different tree items (which seems like it could be potentially confusing).
The wonky stuff I'm doing with the credentials... Basically, the T2 package for registry will ignore the credentials and options that I pass it if `signRequest` is defined.  Since that command is only for backwards compatibility, the easiest way to fix this is to just make it undefined when we need to use it.   Since `parseContext` returns a new object, messing with credentials shouldn't delete `signRequest` everywhere.
=> Fix ADAL tokens, change UI for single/multiple revisions

package-lock.json, package.json, src/commands/createContainerApp/showContainerAppCreated.ts, src/commands/deployImage/deployImage.ts, src/tree/ContainerAppTreeItem.ts
Also marked the "@azure/container-registry": "1.0.0-beta.5" package.  There's a change in 1.0.0 that causes ADAL tokens to not work again.  This is a temporary fix and I'll file an issue against the sdk
=> Browse after revision update

package-lock.json, package.json, src/commands/createContainerApp/ContainerAppCreateStep.ts, src/commands/deployImage/deployImage.ts, src/commands/deployImage/getContainerNameForImage.ts
Fixes https://github.com/microsoft/vscode-azurecontainerapps/issues/122
Fixes https://github.com/microsoft/vscode-azurecontainerapps/issues/19
`.` are common in tags, but not allowed for container app names.  Since this is automatically generated, it was blocking people from creating with certain tags.
=> Correctly parse container image name and fix name regex

package-lock.json, package.json, src/commands/chooseRevisionMode.ts, src/commands/createContainerApp/ContainerAppCreateStep.ts, src/commands/createContainerApp/ContainerAppNameStep.ts, src/commands/createContainerApp/IContainerAppContext.ts, src/commands/createManagedEnvironment/IManagedEnvironmentContext.ts, src/commands/createManagedEnvironment/ManagedEnvironmentCreateStep.ts, src/commands/deployImage/IDeployImageContext.ts, src/commands/deployImage/deployImage.ts, src/commands/ingressCommands.ts, src/commands/revisionCommands/changeRevisionActiveState.ts, src/commands/scaling/editScalingRange.ts, src/commands/updateContainerApp.ts, src/tree/ContainerAppTreeItem.ts, src/tree/DaprTreeItem.ts, src/tree/IngressTreeItem.ts, src/tree/ManagedEnvironmentTreeItem.ts, src/tree/RevisionTreeItem.ts, src/tree/RevisionsTreeItem.ts, src/tree/ScaleRuleGroupTreeItem.ts, src/tree/ScaleRuleTreeItem.ts, src/tree/ScaleTreeItem.ts, src/tree/SubscriptionTreeItem.ts, src/utils/azureClients.ts
The SDK has changed yet again, so updating that.  There's a new update command that doesn't require the _full_ container envelope, so I'm using a new PATCH request that merges the changes of JSON objects.
=> Update SDK and remove use of getting secrets

package-lock.json, package.json, src/commands/deployImage/acr/AcrTagListStep.ts
Fixes https://github.com/microsoft/vscode-azurecontainerapps/issues/21
Turns out the problem was the response of the manifest is grouped by the updated date. Previously, I was always grabbing the latest (index 0) manifest and only showing its tags.  Now I reduce it to one array of tags to display all of the tags.
I also went ahead and added descriptions about the last time it was updated. Seemed useful and is modeled after Docker. I believe the timestamps are different because Docker gets the timestamp from the [Docker repository](https://github.com/microsoft/vscode-docker/blob/8746a82b92abf68ee5ddc5a4137b38ff09504dcd/src/tree/registries/dockerV2/DockerV2RepositoryTreeItem.ts#L67-L72) whereas I'm using the ACR response.
=> List all tags in all manifests and display time it was created

src/commands/scaling/addScaleRule/addScaleRule.ts, src/tree/ScaleRuleGroupTreeItem.ts, src/utils/treeUtils.ts
To keep the functionality consistent with how it's implemented in Storage.  We can consolidate if we ever decide we want to move this utility into AzureTools.
=> Refactor findNearestParent to use context values

src/ContainerAppsResolver.ts, src/commands/createContainerApp/ContainerAppCreateStep.ts, src/commands/createManagedEnvironment/ManagedEnvironmentCreateStep.ts, src/constants.ts, src/extension.ts, src/tree/SubscriptionTreeItem.ts
Closes #185 
Added a `View Output` button to the success popup as well as an `activityResult` to the `Activity Log`.
Also did a bit of housekeeping in the `constants` file and the `createChild` method since I was already making changes there for this update.
=> Add increased visibility to the creation of Managed Environments

src/commands/viewProperties.ts, src/constants.ts, src/tree/IAzureResourceTreeItem.ts
I previously added a context RegExp to a different file when there was already a related one in the `constants` file.  Just wanted to consolidate them while it was fresh on my mind.
=> Consolidate `IAzureResource` context constants

src/commands/chooseRevisionMode.ts
Fixes #195 
Changed the order of calls within the `withProgress` method so that the `update` message is displayed at the end of the actual updates (after the `refresh` method is called, rather than before).
=> Display `chooseRevisionMode` update message closer to the end of the update cycle

package-lock.json, package.json, src/utils/azureClients.ts
The dependency has been deprecated in favor of Azure Monitor Query
Edit:  Will just remove the unused package.  Opened a related issue [here](https://github.com/microsoft/vscode-azurecontainerapps/issues/208) for when we add any query support in the future
=> Removed use of deprecated `Azure Log Analytics` package

src/commands/createContainerApp/ContainerAppNameStep.ts
Fixes #171. 
Fixes #37. 
Validation done in the portal:
The error also does not seem to pop up when entering only one character.
=> Fix name validation when creating a container app

package.json, package.nls.json, src/commands/openInPortal.ts, src/commands/registerCommands.ts, src/tree/LogsTreeItem.ts
I noticed `openInPortal` wasn't showing up for the `containerApp` node.  I think it's likely that this is an artifact of when I initially did the unified migration a few months ago.  I think these changes should fix that.
=> Fix `openInPortal`

src/commands/createManagedEnvironment/ManagedEnvironmentCreateStep.ts
Fixes #241 
Removing based on our talk in standup.... 
This is already basically captured with the Activity Log, so no need to show the extra popup anyway.
=> Remove `View Output` popup after creation of Container Apps Environment

.github/workflows/bump-version-pr.yaml
See https://docs.opensource.microsoft.com/releasing/securing-content/github-actions-security-announcement/
and https://github.com/microsoft/github-operations/issues/232
=> Use PAT for version bumper workflow

src/commands/chooseRevisionMode.ts, src/commands/deployImage/deployImage.ts, src/commands/scaling/editScalingRange.ts, src/tree/ContainerAppItem.ts
Children of the CA were updating, but view properties on the Container App wasn't, so switching the node we refresh to the container app environment itself. That way the CA items are recreated.
=> Refresh CAE children instead of trying to refresh individual CAs

src/commands/createContainerApp/IContainerAppContext.ts, src/commands/createContainerApp/ImageSourceListStep.ts, src/commands/createContainerApp/createContainerApp.ts, src/constants.ts
Closes #271 
New image source list step provides the following options:
`Build from project` related choices will be added in future PRs once implemented...
=> Expand image source selection for creating Container Apps

src/commands/createContainerApp/setQuickStartImage.ts, src/commands/imageSource/containerRegistry/acr/AcrListStep.ts, src/commands/imageSource/containerRegistry/acr/AcrRepositoriesListStep.ts, src/commands/imageSource/containerRegistry/getLatestContainerImage.ts, src/constants.ts, src/utils/imageNameUtils.ts
Partially addresses: #304 
Will add a separate PR to address third party registry steps like those associated with Docker Hub.
For this PR, the implementation I've added looks at the current container app image and checks to see if the values can be re-applied for the new deployment.  If it can, it will suggest the value by extracting it and placing it at the top of the list of quick picks and add the description: `(currently deployed)`.  (I'm very open to whatever labels you guys prefer instead.. I am not great with names/descriptions 😅)
Example:
This is different that `(recently used)` in that it always uses the context of the current Container App rather than using your last pick choice.
If the suggested pick is not found, it will default to the old way of categorizing via `(recently …
=> Suggest values during steps when deploying image from ACR

src/commands/imageSource/ImageSourceListStep.ts
We don't want this pick to show up when using .dev environment. I also tested it on virtual workspaces and that also seems to cause issues with the AcrRun so also not adding the pick when it is a virtual workspace. 
See [here](https://code.visualstudio.com/api/extension-guides/virtual-workspaces#detect-virtual-workspaces-programmatically) for details on detecting virtual workspaces.
=> Only add `Build from project remotely...` pick if on Desktop

main.js, package-lock.json, package.json, src/browser/fs-extra.ts, src/browser/tar.ts, src/commands/imageSource/buildImageInAzure/UploadSourceCodeStep.ts, src/node/fs-extra.ts, src/node/tar.ts, webpack.config.js
Relies on https://github.com/microsoft/vscode-azuretools/pull/1426
=> Extract fs-extra and tar to node/browser folders so we can alias them in webtarget

.azure-pipelines/common/package.yml
Follows same implementation as  https://github.com/microsoft/vscode-azureresourcegroups/pull/648/files
=> Add build defname to buildnumber

src/commands/createContainerApp/createContainerApp.ts
try/finally without catch blocks bubble up exceptions so this wasn't doing anything. The code in the finally block was originally commented out since `showCreatingChild` already emits a refresh event for the given id.
=> Remove unused try/finally

src/commands/deleteManagedEnvironment/deleteManagedEnvironment.ts, src/tree/ContainerAppItem.ts, src/tree/TreeItemState.ts
I'm cleaning up and fixing known bugs in `TreeItemState`. I'm preparing for it to be added to utils and shared between the extensions. Expect more follow-up PRs related to this stuff.
There was a super tiny bug when deleting a tree item where the "Deleting..." description would clear before the tree item was actually removed from the tree.
To fix this, we can simply avoid emitting an update event after we update the tree item state to remove the temporary description. That way the temporary description remains until the tree item is refreshed by someone/something else. In the case of delete, the children of the parent are refreshed, and the item is removed.
To do this, I added a `suppressRefresh` option to `TreeItemState#update`. As well as a `dontRefreshOnRemove` option to …
=> Add `showDeleting` method to `TreeItemState`

src/commands/imageSource/buildImageInAzure/DockerFileItemStep.ts, src/utils/workspaceUtils.ts
Fixes #296. 
Filtering was causing errors so just showing all file types now. 
Had to make a change in workspaceUtils since `selectWorkSpaceFile` returns an fsPath which causes errors. I checked to see if this caused issues with environment variables since `selectWorkSpaceFile` is used there but it seems to still be getting the data correctly.
=> Fix Dockerfile not showing when clicking "Browse..."

src/tree/scaling/ScaleItem.ts
Reverts microsoft/vscode-azurecontainerapps#339
I totally blanked here, removing this tells VS Code that the item has no children.
=> Revert "Don't hardcode ScaleItem collapsibleState"

src/tree/ContainerAppItem.ts
This error started showing up after updating the API version to add log streams. 
We basically should allow null values but still want to make sure values are not undefined.
=> Fix error with `Deploy to Container App...`

src/commands/logStream/startStreamingLogs.ts
Based on feedback from Megan, this types-only change makes it possible to pass in only what the function needs and nothing more. In this case, you no longer need to pass an entire `ContainerAppItem`, only `subscription`, and `containerApp`.
=> Improve parameter type for `startStreamingLogs`

package.json, src/commands/revisionCommands/changeRevisionActiveState.ts, src/tree/RevisionItem.ts
=> Remove Activate, Deactivate and Restart Revision Commands when not applicable 

.github/compliance/inventory.yml
Testing this config in ACA first before adding to our other repositories...
As part of completing the `Asset Management` portion of our assessment this year, we are required to ensure our repositories are properly linked up through the Service Tree.  Our repositories weren't showing up in searches when I last checked with Jing and Misty who have admin privilege.  I reached out and was told that our repos need to have the below configuration to be properly registered:
https://eng.ms/docs/cloud-ai-platform/devdiv/one-engineering-system-1es/1es-docs/policy-service/ghae-repo-inventory
=> Setup for GHAE Repository Inventory

package.json, resources/02889-icon-menu-Container-Revision-Management.svg, src/commands/ingress/editTargetPort/editTargetPort.ts, src/commands/ingress/toggleIngressVisibility/toggleIngressVisibility.ts, src/commands/registerCommands.ts, src/commands/revision/activateRevision.ts, src/commands/revision/changeRevisionActiveState.ts, src/commands/revision/chooseRevisionMode.ts, src/commands/revision/deactivateRevision.ts, src/commands/revision/restartRevision.ts, src/tree/ContainerAppItem.ts, src/tree/configurations/ConfigurationItem.ts, src/tree/configurations/DaprItem.ts, src/tree/configurations/IngressItem.ts, src/tree/revisionManagement/RevisionItem.ts, src/tree/revisionManagement/RevisionsItem.ts, src/tree/scaling/ScaleRuleGroupItem.ts
Builds on top of this work: #379 
Closes #380 
Summary of work:
- Reorganized some files
- Moved some of the revision commands off of the `ContainerAppItem` to the `RevisionItem` and `RevisionsItem`
- Renamed/restructured revision context values
- Add view properties to the newer `ConfigurationItem`
- Add new `Revision Management` icon
- Some minor related prep work for the upcoming revision draft PRs
=> Reconfigure files and commands to fit the new revision management UI

package.json, package.nls.json, src/commands/registerCommands.ts, src/commands/revisionDraft/deployRevisionDraft/DeployRevisionDraftConfirmStep.ts, src/commands/revisionDraft/deployRevisionDraft/DeployRevisionDraftStep.ts, src/commands/revisionDraft/deployRevisionDraft/IDeployRevisionDraftContext.ts, src/commands/revisionDraft/deployRevisionDraft/deployRevisionDraft.ts, src/constants.ts, src/tree/ContainerAppItem.ts, src/tree/revisionManagement/RevisionDraftItem.ts, src/tree/scaling/ScaleItem.ts
Closes #311 
[Demo](https://microsoft-my.sharepoint.com/:v:/p/matfisher/IQBFu96qLyiJRbgNBIHUEt8rAZwOtVW_H595XC9F_IUqwYg?e=VOK9c5) (Same as the one shown in previous revision draft PRs)
=> Add `deployRevisionDraft` support for all revision modes

src/commands/secret/addSecret/SecretNameStep.ts
Closes #421 
Remove the `.` symbol and just use the default (`-`).
Turns out the portal allows `.` but the service itself doesn't allow this.
=> Update secret name validation to not allow `.`

src/commands/deleteContainerApp/DeleteAllContainerAppsStep.ts, src/commands/deleteManagedEnvironment/DeleteEnvironmentConfirmationStep.ts, src/commands/deleteManagedEnvironment/DeleteManagedEnvironmentStep.ts, src/commands/deleteManagedEnvironment/IDeleteManagedEnvironmentContext.ts, src/commands/deleteManagedEnvironment/deleteManagedEnvironment.ts
=> Update `deleteManagedEnvironment` activity messages and general housekeeping

package-lock.json, package.json
Fixes #429. 
Upgrading the package to the most recent beta version allowed new container apps to be created under the new V2 environments with no error. I also tested under the old type of environments and was still able to create, delete, update image, and change revision modes.
=> Update arm-appcontainers package for new V2 environments

package.json, package.nls.json, src/commands/deployImage/imageSource/containerRegistry/acr/createAcr/CreateAcrContext.ts, src/commands/deployImage/imageSource/containerRegistry/acr/createAcr/ICreateAcrContext.ts, src/commands/deployImage/imageSource/containerRegistry/acr/createAcr/RegistryCreateStep.ts, src/commands/deployImage/imageSource/containerRegistry/acr/createAcr/RegistryNameStep.ts, src/commands/deployImage/imageSource/containerRegistry/acr/createAcr/SkuListStep.ts, src/commands/deployImage/imageSource/containerRegistry/acr/createAcr/createAcr.ts, src/commands/registerCommands.ts
=> Add Create Azure Container Registry command

src/commands/secret/addSecret/SecretNameStep.ts, src/utils/validateUtils.ts, test/validateUtils.test.ts
Closes #437 
Added the non-repeat option because a lot of Azure resources have this naming restriction and I'd like to be able to leverage this option for upcoming work.
=> Add `canSymbolsRepeat` option to `validateUtils` and improve invalid input messages

src/commands/EXECUTE_PRIORITY.md, src/commands/createContainerApp/ContainerAppCreateStep.ts, src/commands/createManagedEnvironment/LogAnalyticsCreateStep.ts, src/commands/deployImage/ContainerAppUpdateStep.ts, src/commands/deployImage/imageSource/buildImageInAzure/BuildImageStep.ts, src/commands/deployImage/imageSource/buildImageInAzure/RunStep.ts, src/commands/deployImage/imageSource/buildImageInAzure/TarFileStep.ts, src/commands/deployImage/imageSource/buildImageInAzure/UploadSourceCodeStep.ts, src/commands/deployImage/imageSource/containerRegistry/ContainerRegistryImageConfigureStep.ts, src/commands/deployImage/imageSource/containerRegistry/acr/createAcr/RegistryCreateStep.ts, src/commands/ingress/disableIngress/DisableIngressStep.ts, src/commands/ingress/editTargetPort/TargetPortUpdateStep.ts, src/commands/ingress/enableIngress/EnableIngressStep.ts, src/commands/ingress/toggleIngressVisibility/ToggleIngressVisibilityStep.ts, src/commands/revisionDraft/deployRevisionDraft/DeployRevisionDraftStep.ts, src/commands/scaling/addScaleRule/AddScaleRuleStep.ts, src/commands/secret/addSecret/SecretCreateStep.ts, src/commands/secret/deleteSecret/SecretDeleteStep.ts, src/commands/secret/editSecret/SecretUpdateStep.ts
As part of the express deploy command work, I'm revisiting all the execute step priorities to ensure creations are completed in the correct order (a lot of these commands were being called programmatically by the user before, and so the execute step priority values hadn't been especially important).  
Let me know if you think a general priority markdown file like this would be useful for tracking.
=> Enforce new execute step priority ranges

src/utils/activityUtils.ts, src/utils/settingUtils.ts
So I forgot that the old `getWorkspaceSetting` also would check up to the user's global setting due to it being tied to `projectConfiguration.get`.  I originally thought the name was kind of misleading since it didn't always grab a workspace setting, but I forgot to mirror that hidden behavior for `createActivityContext` after I refactored.  
With this more generic `getSetting` implementation addition, we can carry over the same behavior while keeping the function names more in line with their intended behavior.
=> Add `settingsUtil.getSetting`

src/commands/ingress/IngressUpdateBaseStep.ts, src/commands/ingress/IngressUpdateStepBase.ts, src/commands/ingress/disableIngress/DisableIngressStep.ts, src/commands/ingress/disableIngress/disableIngress.ts, src/commands/ingress/editTargetPort/TargetPortUpdateStep.ts, src/commands/ingress/editTargetPort/editTargetPort.ts, src/commands/ingress/enableIngress/EnableIngressStep.ts, src/commands/ingress/enableIngress/enableIngress.ts, src/commands/ingress/toggleIngressVisibility/ToggleIngressVisibilityStep.ts, src/commands/ingress/toggleIngressVisibility/toggleIngressVisibility.ts
Since some of these steps are re-usable, it doesn't make sense to make activity title and refresh changes in the execute steps themselves.  I wish I had realized this earlier, but I pulled these behaviors out and attached them to the commands instead and will implement this way going forward.
=> Clean up `Ingress` tree refreshing and activity title behaviors

src/commands/createContainerApp/ContainerAppCreateStep.ts, src/commands/createContainerApp/createContainerApp.ts
- Set the `resourceGroup` rather than the `newResourceGroupName` when pulling the value from the parent node (this was causing issues elsewhere)
- Make activity title consistent with how the rest of the extension is using caps
=> `createContainerApp` improvements

src/commands/revisionDraft/RevisionDraftFileSystem.ts
I was looking over the revision draft file IDs and realized that since it was only using the container app name, and since container app names are not globally unique, that there is a small possibility of overlapping draft names.  To combat this, I've decided on producing a shortened version of the normal container app ID and using that identifier instead to ensure uniqueness.  Let me know what you think!
=> Update revision draft file IDs to ensure uniqueness

src/commands/deployWorkspaceProject/deployWorkspaceProject.ts, src/commands/deployWorkspaceProject/getDefaultValues/getDefaultContainerAppsResources.ts
Some of this logic can probably be eventually re-purposed into a `ManagedEnvironmentListStep`
=> Add ability to choose an existing managed environment for `deployWorkspaceProject`

src/commands/createContainerApp/createContainerApp.ts
I think it looks better shorter, what do you think?
vs.
=> Shorten the container app creation description

src/commands/revisionDraft/RevisionDraftUpdateBaseStep.ts
Based on feedback, changing from the top image to the bottom one:
=> Simplify deploy pop-up wording

src/commands/revisionDraft/RevisionDraftFileSystem.ts, src/commands/revisionDraft/createRevisionDraft.ts, src/commands/revisionDraft/deployRevisionDraft/DeployRevisionDraftStep.ts, src/commands/revisionDraft/deployRevisionDraft/deployRevisionDraft.ts, src/commands/revisionDraft/discardRevisionDraft.ts, src/tree/revisionManagement/RevisionDraftItem.ts, src/tree/revisionManagement/RevisionsItem.ts
Anthony brought this scenario up a while back.  When running certain draft commands without the tree expanded, it may be difficult to locate changes.  I did my best to expand basically as high as we can currently go with reveal.  I can't reveal the actual container app because the id is currently tied to the hidden resource and not the container apps shown under the managed environment group.
I also moved the `showCreatingChild` into the `RevisionDraftFileSystem` create method so that the tree item shows up properly regardless of the command entry-point.
=> Increase draft creation visibility in the tree view

src/commands/secret/deleteSecret/SecretDeleteConfirmStep.ts
Adding more info to the delete confirmation message to more resemble this message in the portal.
=> Change "Delete Secret..." command confirmation message

src/commands/revision/changeRevisionActiveState.ts
=> Fix command palette support for `restartRevision`

src/commands/deployWorkspaceProject/deployWorkspaceProject.ts
I was thinking it may make more sense to set the location to match the highest resource specificity.  
Previously I stopped at the managed environment level, but started thinking that maybe it makes more sense to override with the container app location if one is found.  Pretty much the only resource which would remain to be created in that scenario would be the container registry.. Thoughts?
=> Update location setting behavior for `deployWorkspaceProject`

src/commands/ContainerAppOverwriteConfirmStep.ts
I had a container app that was built through VS Code produce an empty array (not sure why because they're usually `undefined`), and it was prompting me that there were unsupported features that may be lost.  I started inspecting and the culprit was an empty array `[]`.  
I think in the case of an empty array, it's essentially equal to the `undefined` scenarios, so we probably can skip showing this if length is `0` or `undefined`.
=> Don't flag empty arrays when checking for unsupported features

src/commands/image/imageSource/containerRegistry/getRegistryCredentialsAndSecrets.ts
=> Remove symbols from `loginServer` when building `passwordSecretRef`

package-lock.json, package.json
Adds error tree items by default on fail to the activity children
=> Bump utils to `v2.1.3`

src/commands/deployWorkspaceProject/getDefaultValues/DefaultResourcesNameStep.ts, src/commands/image/imageSource/containerRegistry/acr/createAcr/RegistryNameStep.ts, test/deployWorkspaceProject/DefaultResourcesNameStep/DefaultResourcesNameStep.test.ts, test/deployWorkspaceProject/DefaultResourcesNameStep/MockDefaultResourcesNameStep.ts
Because registry names have to be globally unique, it's almost guaranteed to have failed the workspace name check. This ensures that the registry name will almost always be unique.
=> Automatically generate a unique name for registries

src/commands/createContainerApp/createContainerApp.ts, src/commands/deployWorkspaceProject/deployWorkspaceProject.ts
Fixes #556 
Currently known to affect ribbon commands.
=> If an incompatible tree item is passed, treat it as if no tree item was passed

src/commands/image/imageSource/buildImageInAzure/TarFileStep.ts, src/utils/settingUtils.ts, src/utils/workspaceUtils.ts
Although it ends up working either way due to URI path normalization in `AzExtFsExtra`, it's more correct and less ambiguous to refer to `fsPath` instead of `path`.
=> Ensure file system paths use the `fsPath` property

.vscode/settings.json, src/commands/deployWorkspaceProject/DeployWorkspaceProjectConfirmStep.ts, src/commands/deployWorkspaceProject/DeployWorkspaceProjectContext.ts, src/commands/deployWorkspaceProject/deployWorkspaceProject.ts, src/commands/deployWorkspaceProject/deployWorkspaceProjectInternal.ts, src/commands/deployWorkspaceProject/getDefaultValues/getDefaultContextValues.ts, src/utils/activity/ExecuteActivityOutputStepBase.ts
Add internal implementation which will be shared by the API command and the normal version of the command.
Helps to decouple this implementation before setting up the API in this PR:
https://github.com/microsoft/vscode-azurecontainerapps/pull/578
=> Add `deployWorkspaceProjectInternal`

src/commands/createContainerApp/ContainerAppCreateStep.ts, src/commands/createManagedEnvironment/LogAnalyticsCreateStep.ts, src/commands/createManagedEnvironment/ManagedEnvironmentCreateStep.ts, src/commands/deployWorkspaceProject/DeployWorkspaceProjectSaveSettingsStep.ts, src/commands/deployWorkspaceProject/deployWorkspaceProjectInternal.ts, src/commands/image/imageSource/ContainerAppUpdateStep.ts, src/commands/image/imageSource/EnvironmentVariablesListStep.ts, src/commands/image/imageSource/buildImageInAzure/BuildImageStep.ts, src/commands/image/imageSource/buildImageInAzure/RunStep.ts, src/commands/image/imageSource/buildImageInAzure/UploadSourceCodeStep.ts, src/commands/image/imageSource/containerRegistry/acr/createAcr/RegistryCreateStep.ts, src/commands/ingress/IngressPromptStep.ts, src/commands/ingress/enableIngress/EnableIngressStep.ts
Update activity log error items to use `GenericParentTreeItem` so that any additional error messages can be automatically appended as a child of the step that threw it.
Example:
=> Convert errors to use `GenericParentTreeItem` and add more specific context values

.vscode/settings.json, package-lock.json, package.json, src/commands/image/imageSource/buildImageInAzure/RunStep.ts
Fixes #562.
I arbitrarily chose 3 retries since that should cover the timing issue and building the image takes a bit of time. Let me know if anyone disagrees with that choice. 
I also tried a couple of times to test the retries but I could only get it to work on the first try. Guess our code is just too good 🤪
=> Add retries for `Build image in Azure`

src/commands/image/imageSource/buildImageInAzure/UploadSourceCodeStep.ts
Closes #598 
ACR does not support the `--platform` flag and will automatically error out if it detects this flag.  They have an open issue for it, but we have no idea when it will be addressed and enough people are running into it that we have been asked to help address this on our end.
Updated activity log:
Big thanks and credit out to Anthony Chu for helping us come up with the bulk of the core logic for custom Dockerfile replacement! :)
=> Automatically remove the `--platform` flag from the Dockerfile on deployment

src/commands/createContainerApp/ContainerAppNameStep.ts, src/commands/deployWorkspaceProject/getDefaultValues/DefaultResourcesNameStep.ts
Don't allow names to start with a number.
Closes #596
=> Fix default name validation logic for `deployWorkspaceProject`

src/commands/deployWorkspaceProject/deploymentConfiguration/DeploymentConfiguration.ts, src/commands/deployWorkspaceProject/deploymentConfiguration/workspace/DeploymentConfigurationListStep.ts, src/commands/deployWorkspaceProject/deploymentConfiguration/workspace/getWorkspaceDeploymentConfiguration.ts, src/commands/deployWorkspaceProject/settings/DeployWorkspaceProjectSettingsV2.ts
I think adding a UUID for each deployment configuration will give us an easy way to save and overwrite settings.  I'm not sure that there are any other settings that exist that we can check and expect to be unique each and every time.
=> Add a unique ID field to deployment configurations

src/commands/image/imageSource/EnvironmentVariablesListStep.ts, src/utils/workspaceUtils.ts
Fixes https://github.com/microsoft/vscode-azurecontainerapps/issues/451
Note that this only applies for `updateContainerApp` since `deployWorkspace` leverages `getDefaultContextValue` which sets `context.environmentVariables` to `[ ]` if it doesn't detect an `.env` file.
I didn't change this behavior because I figured that we will be altering `deployWorkspace`'s behavior; specifically we'll be looking at an `envPath` setting.
=> Use existing env variables when updating container app if "skipped"

src/commands/deployWorkspaceProject/internal/startingConfiguration/TryUseExistingRegistryStep.ts, src/commands/deployWorkspaceProject/internal/startingConfiguration/getStartingConfiguration.ts
The internal logic presents the last bastion of hope for our users to find a suitable ACR without prompting.  We should do everything we can to assist them out on the cloudy battlefield ☁⚔️
=> Add fallback defaulting logic for ACRs within `deployWorkspaceProjectInternal`

src/commands/deployWorkspaceProject/deploymentConfiguration/getTreeItemDeploymentConfiguration.ts, src/commands/deployWorkspaceProject/deploymentConfiguration/workspace/DeploymentConfigurationListStep.ts, src/commands/deployWorkspaceProject/deploymentConfiguration/workspace/azureResources/AzureResourceVerifyStepBase.ts, src/commands/deployWorkspaceProject/deploymentConfiguration/workspace/azureResources/ContainerAppVerifyStep.ts, src/commands/deployWorkspaceProject/deploymentConfiguration/workspace/azureResources/ContainerRegistryVerifyStep.ts, src/commands/deployWorkspaceProject/deploymentConfiguration/workspace/azureResources/ResourceGroupVerifyStep.ts, src/commands/deployWorkspaceProject/deploymentConfiguration/workspace/azureResources/TryUseExistingWorkspaceRegistryStep.ts, src/commands/deployWorkspaceProject/deploymentConfiguration/workspace/getWorkspaceDeploymentConfiguration.ts
- Use `keyof` for key properties
- Reorganize `azureResource/` files
=> Improve type safety and reorganize resource verification files

src/commands/createManagedEnvironment/IManagedEnvironmentContext.ts, src/commands/createManagedEnvironment/LogAnalyticsCreateStep.ts, src/commands/deployWorkspaceProject/internal/DefaultResourcesNameStep.ts, src/commands/deployWorkspaceProject/internal/DeployWorkspaceProjectSaveSettingsStep.ts
If able, will attach suffixes to names (e.g. `-ca`, `-env`, `-rg`, `-log`, etc.)
=> Try to add default name suffixes to resources in `deployWorkspaceProjectInternal`

src/commands/deployWorkspaceProject/internal/startingConfiguration/DwpManagedEnvironmentListStep.ts, src/telemetry/deployWorkspaceProjectTelemetryProps.ts
I toyed with the idea of using grouping instead of description. Not sure if we want to go that route though in case we started grouping things by resource group or something.
Also `supressedPersistence` because the (recently used) description looks kind of silly with recommended.
=> Find previously deployed to managed environment and recommend them

src/commands/api/deployWorkspaceProjectApi.ts, src/commands/api/getAzureContainerAppsApiProvider.ts, src/commands/deployWorkspaceProject/internal/AppResourcesNameStep.ts, src/commands/deployWorkspaceProject/internal/deployWorkspaceProjectInternal.ts
Also, try to name the managed environment after the resource group automatically if one is supplied
=> Small fixes to ensure backwards compatibility with API

src/commands/api/CHANGELOG.md, src/commands/api/getAzureContainerAppsApiProvider.ts
We should have just released the API version at 1.0.0 since 0.0.1 does some funky things with semver. The API itself isn't in preview (even if the extensions are) so there's really no reason to be using 0.0.1 anyway.
=> Upgrade API version to 1.0.1

src/commands/api/CHANGELOG.md, src/commands/api/getAzureContainerAppsApiProvider.ts
Reverts microsoft/vscode-azurecontainerapps#674
We can coordinate a release for Functions and Containers when there's less chaos in the world. Let's just keep the api-version as is for now since it's backwards compatible anyway.
=> Revert "Upgrade API version to 1.0.1"

.azure-pipelines/release.yml
Now that we know it works, I merged the templates into main so we need to use the templates on main instead of my dev branch now.
=> Use main branch of release template

src/tree/ContainerAppItem.ts
=> Add a better error message when trying to expand an app that isn't provisioned yet

src/commands/scaling/scaleRange/editScaleRange.ts, src/utils/revisionDraftUtils.ts
Fix an issue where `editScalingRange` was showing up on other revision items even when a draft node already existed.  In my opinion, it's confusing / doesn't make sense to allow users to try editing other revisions simultaneously when another draft already exists.
=> Don't show `editScalingRange` on another `ScaleItem` if a draft item already exists

src/tree/containers/EnvironmentVariableItem.ts
Closes #766
Environment variables can be the raw entered values, or they can also reference container app secrets.  The secret ref will be a pointer to the secret name only, so it should not be a security concern (the secret value is never shown).
=> Support showing environment variable secret refs

package-lock.json, package.json, package.nls.json, src/commands/image/updateImage/updateImage.ts, src/commands/revisionDraft/RevisionDraftContext.ts, src/commands/revisionDraft/RevisionDraftDeployPromptStep.ts, src/commands/revisionDraft/RevisionDraftUpdateBaseStep.ts, src/commands/scaling/scaleRange/ScaleRangeContext.ts, src/commands/scaling/scaleRange/editScaleRange.ts, src/commands/scaling/scaleRule/ScaleRuleContext.ts, src/commands/scaling/scaleRule/addScaleRule/addScaleRule.ts, src/commands/scaling/scaleRule/deleteScaleRule/deleteScaleRule.ts, src/constants.ts, src/utils/pickItem/pickContainerApp.ts, src/utils/pickItem/pickEnvironment.ts
Discussed this with Nathan a while back, and we agreed it would probably be better to use a quick pick instead of a pop-up window after each command.  This means the prompt to deploy becomes something we ask at the start rather than something we ask after the draft command finishes.
I'm proposing the process now would be - each draft command should push in the following quick pick step as the last prompt:
`new RevisionDraftDeployPromptStep()`
Almost no 'new' logic has actually been added here, mostly prompt logic from the old `RevisionDraftUpdateBaseStep` got moved into the new `RevisionDraftDeployPromptStep`.
Before (informational window):
After (prompt quick pick):
To see in action, you can test with this command:
Edit: I forgot, I also snuck in a small fix for this...
Fixes #683
=> Change draft deploy pop-up from an informational window to a quick pick

src/commands/scaling/scaleRange/editScaleRange.ts
Fixes an issue where we were suggesting outdated input values because we were not updating the scale range with the draft values when a draft was in session.
=> Ensure that the correct initial scale range is pre-populated in input fields

src/tree/ContainerAppItem.ts
I was messing around with this some more, and we really should only throw this error during an active provisioning state which are the two checked in the new if condition.
=> Update `ContainerAppItem` provisioning error conditions

src/commands/api/vscode-azurecontainerapps.api.d.ts
This is already being exported, but I forgot to add the matching API type definition for `deployImage`
=> Update API type definition for `deployImage`

src/commands/environmentVariables/addEnvironmentVariable/EnvironmentVariableNameStep.ts
Fix #871 
Portal doesn't show a validation error message anymore, but just fails if the name isn't suitable.  We'll keep the same rule that they were using / showing before, but update the error message to be better.
=> Fix validation error message for naming environment variables

src/commands/environmentVariables/convertEnvironmentVariable/convertEnvironmentVariable.ts, src/commands/environmentVariables/editEnvironmentVariable/EnvironmentVariableEditDraftStep.ts, src/commands/environmentVariables/editEnvironmentVariable/editEnvironmentVariableName.ts, src/commands/environmentVariables/editEnvironmentVariable/editEnvironmentVariableValue.ts
Fixes #874 
The output strings shown in the issue are [too] generic because I have all environment variable edit commands leveraging the same generic execute step.  The simplest solution I could think of was to just allow passing of the customized strings during instantiation.
=> Add better output log messages when editing environment variables

src/commands/deployContainerApp/deployContainerApp.ts, src/webviews/ConfirmationView.tsx, src/webviews/ConfirmationViewController.ts, src/webviews/OpenConfirmationViewStep.ts, src/webviews/extension-server/WebviewController.ts
This opens the chat and adds a prompt when the copilot button is pressed within the confirmation view. Here is an example of what the prompt looks like and the copilot response:
=> Add functionality to copilot button

main.js, src/webviews/extension-server/WebviewBaseController.ts
Fixes https://github.com/microsoft/vscode-azurecontainerapps/issues/905
Tested the vsix created by this PR and also got Nathan to test it also.
=> Fix webview production 
