- package.json
- package.nls.json
- src/commands/createContainerApp/showContainerAppCreated.ts
- src/tree/ContainerAppTreeItem.ts
- src/tree/KubeEnvironmentTreeItem.ts
Fixes https://github.com/microsoft/vscode-azurecontainerapps/issues/20
> Enable browse command and fix browse

- src/commands/chooseRevisionMode.ts
- src/commands/createContainerApp/ContainerAppCreateStep.ts
- src/constants.ts
- src/tree/RevisionsTreeItem.ts
FIxes https://github.com/microsoft/vscode-azurecontainerapps/issues/44
> Default to creating apps in single revision mode

- package-lock.json
- package.json
- src/commands/createContainerApp/ContainerAppCreateStep.ts
- src/commands/createContainerApp/EnvironmentVariablesListStep.ts
- src/commands/createContainerApp/IContainerAppContext.ts
- src/tree/ManagedEnvironmentTreeItem.ts
- src/tree/SubscriptionTreeItem.ts
- src/utils/workspaceUtils.ts
Fixes https://github.com/microsoft/vscode-azurecontainerapps/issues/32
The UI for the step:
> Add a environment var step in container app creation

- package-lock.json
- package.json
- src/tree/ContainerAppTreeItem.ts
- src/tree/DaprTreeItem.ts
Forgot to PR this one, but just using the new SDK that was published
> Install the new sdk

- src/commands/createContainerApp/ContainerAppCreateStep.ts
- src/commands/deployImage/deployImage.ts
- src/tree/ContainerAppTreeItem.ts
Password names need to be unique.  there should only be one password per registry.  So by naming it by its registry name, should be unique.  We don't want to delete old ones when adding a new one.
> Dont delete registries/secrets, update or add

- src/commands/createContainerApp/IContainerAppContext.ts
- src/commands/deployImage/IDeployImageContext.ts
- src/commands/deployImage/deployImage.ts
Wasn't adding the environment variables to the new image when updating container app.
> Update env variables on update image container

- src/tree/ContainerAppTreeItem.ts
- src/tree/DaprTreeItem.ts
Fixes https://github.com/microsoft/vscode-azurecontainerapps/issues/55
> Add the dapr tree back in

- src/commands/createManagedEnvironment/LogAnalyticsCreateStep.ts
Fixes https://github.com/microsoft/vscode-azurecontainerapps/issues/86
> Add created log message

- main.js
- package.json
- src/commands/createContainerApp/IContainerAppContext.ts
- src/commands/createContainerApp/TargetPortStep.ts
- src/commands/ingressCommands.ts
Fixes https://github.com/microsoft/vscode-azurecontainerapps/issues/73
> Default value is current port number when editing target port

- src/tree/SubscriptionTreeItem.ts
Fixes https://github.com/microsoft/vscode-azurecontainerapps/issues/108
> Add operationInsights verifyProviderStep

- package-lock.json
- package.json
- package.nls.json
- src/commands/registerCommands.ts
- src/commands/scaling/editScalingRange.ts
- src/tree/ContainerAppTreeItem.ts
- src/tree/ScaleTreeItem.ts
Fixes https://github.com/microsoft/vscode-azurecontainerapps/issues/99
And fixes:
> "Scaling" under app shouldn't appear if in multi-revision mode
Looking at this code though made me realize that I am going to have to _heavily_ refactor some stuff 🤦‍♂️
> Allow users to edit scale replica ranges

- package-lock.json
- package.json
- src/commands/createManagedEnvironment/ManagedEnvironmentCreateStep.ts
- src/commands/createManagedEnvironment/createManagedEnvironment.ts
Fixes https://github.com/microsoft/vscode-azurecontainerapps/issues/117
> Move created env message to CreateStep

- package-lock.json
- package.json
- src/commands/scaling/editScalingRange.ts
Fixes https://github.com/microsoft/vscode-azurecontainerapps/issues/118
> Check that max replicas is greater than 0

- package-lock.json
- package.json
- src/commands/scaling/editScalingRange.ts
- src/tree/ContainerAppTreeItem.ts
- src/tree/RevisionTreeItem.ts
Fixes https://github.com/microsoft/vscode-azurecontainerapps/issues/119
> Use pickTreeItemImpl to pick up ScaleTreeItem in cmd palette

- package-lock.json
- package.json
- src/commands/createContainerApp/TargetPortStep.ts
Fixes https://github.com/microsoft/vscode-azurecontainerapps/issues/116
> Validate port number is whole integer

- package-lock.json
- package.json
- src/tree/ContainerAppTreeItem.ts
Fixes https://github.com/microsoft/vscode-azurecontainerapps/issues/149
> Refresh all tree children on ca refresh

- package-lock.json
- package.json
Fixes https://github.com/microsoft/vscode-azurecontainerapps/issues/135
> Update packages for telemetry updates and vs code engine 🚒

- package-lock.json
- package.json
- src/commands/createManagedEnvironment/LogAnalyticsCreateStep.ts
> Change Log Analytics Location to Match Managed Environment Location

- src/commands/createContainerApp/ContainerAppNameStep.ts
- src/commands/createManagedEnvironment/ManagedEnvironmentNameStep.ts
Fixes https://github.com/microsoft/vscode-azurecontainerapps/issues/65
Also got rid of the `checkNameLength`.  It wasn't working properly and would let invalid names slip in.  Not worth the slight UI enhancements it brought.
> Fix name steps

- src/tree/ContainerAppTreeItem.ts
There was a weird bug that @microfish91 was running into.  Scale rules are supposed to be revision specific, but for some reason, the data in Container Apps was grabbing every single scale rule across all revisions instead of the latest one. 
It seems like a bug on the service end, because I'm pretty sure that it only supposed to return the latest revision template information, but it seems easy enough for us to just get the revision data and use it as needed.
> Use revision specific data to create scale rule

- package.json
> Remove extra `view properties` from Container Apps Environment context menu

- src/tree/ContainerAppTreeItem.ts
- src/tree/DaprTreeItem.ts
> Added differentiating enabled/disabled Dapr tree items

- src/commands/chooseRevisionMode.ts
> Refresh parent node after calling command `chooseRevisionMode`

- src/commands/registerCommands.ts
> Update delete Managed Environment expected context value to a regular expression

- src/commands/scaling/editScalingRange.ts
> Display `editScalingRange` update message closer to the end of the update cycle

- package-lock.json
- package.json
- src/commands/registerCommands.ts
- src/extension.ts
I think these are all the necessary changes, please let me know if I missed something :)
Issues I noticed:
1) Duplicate resources showing up (seems like people are aware of this issue and there may already be a fix in the works)
2) The Resource Groups branch being used is an older version without our newer Container Apps title and logo changes (should get fixed naturally when we merge with main, but just wanted to put it on our radar so we make sure to verify this once we merge)
Edit: Noticing some issues related to executing commands from the group level node, will discuss off GitHub
Edit: Reverted the `package.json` view ID's back to original based on our discussions
> V2 Compatibility Changes

- src/tree/ResolvedContainerAppsResource.ts
> Change activity log to "Delete Container Apps environment"

- src/commands/deleteManagedEnvironment/DeleteEnvironmentConfirmationStep.ts
> Be consistent with `Container Apps: Delete Confirmation` setting

- src/commands/deleteManagedEnvironment/DeleteManagedEnvironmentStep.ts
> Add information to the Activity Log that deleting a CAE will take a while

- src/tree/RevisionsItem.ts
> Add description to revisions item

- src/tree/IngressItem.ts
Fixes https://github.com/microsoft/vscode-azurecontainerapps/issues/247
> Fix edit target port from context menu of target port node

- src/tree/IngressItem.ts
Started working on a fix for this until I realized Alex already fixed this on main... so I just cherry-picked @alexweininger's work.  From what I can tell, it fixes our issue in .dev as well.
Concerning:
#239 Edit Target Port
> Cherry-pick edit target port fix

- package-lock.json
- package.json
> Upgrade azext-utils (0.5.1)

- package-lock.json
- package.json
- src/commands/deploy/deployFromRegistry/IDeployFromRegistryContext.ts
- src/commands/deploy/deployFromRegistry/acr/AcrListStep.ts
- src/commands/deploy/deployFromRegistry/acr/RegistryEnableAdminUserStep.ts
- src/commands/deploy/deployFromRegistry/acr/listCredentialsFromRegistry.ts
- src/utils/azureClients.ts
- src/utils/imageNameUtils.ts
This dependency needs to be updated for the docker `buildImageInAzure` code migration.
> Fix errors related to updating "@azure/arm-containerregistry" dependency

- src/commands/deploy/IDeployBaseContext.ts
- src/commands/deploy/ImageSourceListStep.ts
- src/commands/deploy/buildImageInAzure/BuildFromProjectListStep.ts
- src/constants.ts
Connects code from #287 to the create path. 
Contributes to #286
> Connect buildImageInAzure to Create Container App

- src/commands/createContainerApp/ContainerAppCreateStep.ts
Should show the simpler UI as the default
> Default to single revision mode when creating a container app

- src/commands/imageSource/buildImageInAzure/UploadSourceCodeStep.ts
> Fix create a container app when selecting "Build from project remotely using ACR"

- src/tree/TreeItemState.ts
Now creating... tree items can be displayed for each ongoing create operation.
> Allow multiple temporary child tree items

- src/tree/scaling/ScaleItem.ts
> Don't hardcode ScaleItem collapsibleState

- package-lock.json
- package.json
- package.nls.json
- src/commands/connectToGitHub/IConnectToGitHubContext.ts
- src/commands/connectToGitHub/connectToGitHub.ts
- src/commands/registerCommands.ts
- src/gitHub/GitHubBranchListStep.ts
- src/gitHub/GitHubOrgListStep.ts
- src/gitHub/GitHubRepositoryListStep.ts
- src/gitHub/IGitHubContext.ts
- src/gitHub/createOctokitClient.ts
- src/gitHub/getAuthenticatedUser.ts
- src/gitHub/getBranches.ts
- src/gitHub/getGitHubAccessToken.ts
- src/gitHub/getOrgs.ts
- src/gitHub/getRepositories.ts
- src/gitHub/getUserOrgs.ts
Part 1 of this roadmap:  https://github.com/microsoft/vscode-azurecontainerapps/issues/313#issuecomment-1518418209
For now, there is only one command entry point via the command palette.  The `Actions` node will be added in a follow-up PR and will eventually become the primary entry point for connecting a GitHub repository through the tree view.
> Scaffold `connectToGitHub` command and add `Octokit` support

- package.json
- package.nls.json
- src/commands/disconnectRepo/GitHubRepositoryDisconnectStep.ts
- src/commands/disconnectRepo/IDisconnectRepoContext.ts
- src/commands/disconnectRepo/disconnectRepo.ts
- src/commands/registerCommands.ts
Part 4 of https://github.com/microsoft/vscode-azurecontainerapps/issues/313#issuecomment-1518418209
> Disconnect from a GitHub repository

- src/commands/gitHub/connectToGitHub/DockerfileLocationInputStep.ts
- src/commands/gitHub/connectToGitHub/GitHubRepositoryConnectStep.ts
- src/commands/gitHub/connectToGitHub/IConnectToGitHubContext.ts
- src/commands/gitHub/connectToGitHub/ServicePrincipalIdInputStep.ts
- src/commands/gitHub/connectToGitHub/ServicePrincipalSecretInputStep.ts
- src/commands/gitHub/connectToGitHub/connectToGitHub.ts
- src/commands/gitHub/connectToGitHub/getContainerAppSourceControl.ts
- src/commands/gitHub/connectToGitHub/isGitHubConnected.ts
- src/commands/gitHub/disconnectRepo/GitHubRepositoryDisconnectStep.ts
- src/commands/gitHub/disconnectRepo/IDisconnectRepoContext.ts
- src/commands/gitHub/disconnectRepo/disconnectRepo.ts
- src/commands/registerCommands.ts
- src/tree/gitHub/ActionsTreeItem.ts
Put all the GitHub commands in one folder.  We'll be adding at least one more command so it probably makes sense to group them together
`commands/gitHub/<commands now go here>`
> Consolidate GitHub commands

- package.json
- package.nls.json
- src/commands/gitHub/openGitHubRepo.ts
- src/commands/registerCommands.ts
Open GitHub repository command (opens link in browser)...
> Add `OpenGitHubRepo` command

- CHANGELOG.md
- package-lock.json
- package.json
The base branch is created from 54ab060f1e7247c01b0773633dd97a63d7bed279
> Add commands to focus view

- src/tree/ConfigurationItem.ts
- src/tree/ContainerAppItem.ts
- src/tree/LogsItem.ts
- src/tree/RevisionItem.ts
- src/tree/RevisionsItem.ts
Some changes to the UI:
OLD MULTIPLE:
NEW MULTIPLE: (I want to use this icon for Revision management)
OLD SINGLE:
NEW SINGLE:
> Changes to the container apps UI

- .github/compliance/inventory.yml
The suggested changes did not work so reverting..
Reason: https://github.com/microsoft/vscode-azurecontainerapps/pull/383#issuecomment-1584491586
> Revert GHAE changes

- package-lock.json
- package.json
Fixes a missing type definition dependency error showing up for `@microsoft/vscode-azureresources-api`
> Add missing type dependency `@azure/ms-rest-azure-env`

- package.json
- package.nls.json
- src/commands/registerCommands.ts
- src/commands/revisionDraft/createRevisionDraft.ts
- src/commands/revisionDraft/discardRevisionDraft.ts
- src/commands/revisionDraft/editRevisionDraft.ts
- src/constants.ts
- src/tree/revisionManagement/RevisionItem.ts
- src/tree/revisionManagement/RevisionsItem.ts
- src/tree/scaling/ScaleItem.ts
- src/utils/pickContainerApp.ts
- src/utils/pickRevisionItem.ts
**Background**:
- See #311 
**What is coming down the line**:
- Deploy revision draft command (all revision modes)
**Demo of the full feature**:
- [Demo](https://microsoft-my.sharepoint.com/:v:/p/matfisher/IQBFu96qLyiJRbgNBIHUEt8rAZwOtVW_H595XC9F_IUqwYg?e=VOK9c5) (Same as the one shown in the single revisions PR)
> Add revision draft support (multiple revisions mode)

- extension.bundle.ts
- package.json
- package.nls.json
- src/commands/registerCommands.ts
- src/commands/secret/ISecretContext.ts
- src/commands/secret/addSecret/SecretCreateStep.ts
- src/commands/secret/addSecret/SecretNameStep.ts
- src/commands/secret/addSecret/SecretValueStep.ts
- src/commands/secret/addSecret/addSecret.ts
- src/utils/validateUtils.ts
- test/validateUtils.test.ts
> Support for adding secrets

- package.json
- package.nls.json
- src/commands/registerCommands.ts
- src/commands/secret/editSecret/SecretUpdateStep.ts
- src/commands/secret/editSecret/editSecretName.ts
- src/commands/secret/editSecret/editSecretValue.ts
> Add support for editing secrets

- src/commands/revision/chooseRevisionMode/ChangeRevisionModeStep.ts
> Remove period in change revision mode acitivity title

- src/commands/deployWorkspaceProject/getDefaultValues/getWorkspaceProjectPaths.ts
- src/utils/workspaceUtils.ts
Related to #425 
Not dependent on any of the other existing `deployWorkspaceProject` PRs
> Add `Dockerfile` selection logic to `deployWorkspaceProject`

- src/commands/deployImage/imageSource/buildImageInAzure/BuildImageStep.ts
- src/utils/activity/ExecuteActivityOutputStepBase.ts
Refactored the logic a bit more based on some good suggestions from @nturinski
> Improve `ExecuteActivityOutputStepBase`

- package.nls.json
This command has no prompts after so removing the "..."
> Remove "..." from "Discard Changes..." command

- src/commands/deleteManagedEnvironment/DeleteEnvironmentConfirmationStep.ts
> Update `deleteManagedEnvironment` setting utils call

- src/commands/scaling/scaleRule/deleteScaleRule/deleteScaleRule.ts
> Fix empty prompt showing when deleting a scale rule

- src/commands/revisionDraft/RevisionDraftUpdateBaseStep.ts
> Use a fresh context when running the deploy command from a deploy pop-up

- package-lock.json
- package.json
> Upgrade utils dependency to v2.1.2

- src/commands/createContainerApp/ContainerAppCreateStep.ts
- src/commands/createContainerApp/ContainerAppNameStep.ts
- src/commands/createContainerApp/CreateContainerAppContext.ts
- src/commands/createContainerApp/createContainerApp.ts
- src/commands/createContainerApp/setQuickStartImage.ts
- src/commands/deployWorkspaceProject/DeployWorkspaceProjectContext.ts
- src/commands/image/imageSource/ImageSourceListStep.ts
- src/commands/image/imageSource/containerRegistry/acr/AcrListStep.ts
- src/commands/ingress/IngressContext.ts
- src/commands/ingress/IngressPromptStep.ts
- src/commands/ingress/disableIngress/DisableIngressStep.ts
- src/commands/ingress/disableIngress/disableIngress.ts
- src/commands/ingress/editTargetPort/TargetPortInputStep.ts
- src/commands/ingress/editTargetPort/TargetPortUpdateStep.ts
- src/commands/ingress/editTargetPort/getDefaultPort.ts
- src/commands/ingress/enableIngress/EnableIngressStep.ts
- src/commands/ingress/enableIngress/IngressVisibilityStep.ts
- src/commands/ingress/enableIngress/enableIngress.ts
- src/commands/ingress/isIngressEnabled.ts
- src/commands/ingress/toggleIngressVisibility/ToggleIngressVisibilityStep.ts
- src/commands/ingress/toggleIngressVisibility/toggleIngressVisibility.ts
- src/telemetry/IngressTelemetryProps.ts
- src/telemetry/commandTelemetryProps.ts
- test/ingress/getDefaultPort.test.ts
- Added `CreateContainerAppTelemetryProps` 
- Renamed the `ICreateContainerAppContext` -> `CreateContainerAppContext`
- Added more ingress telemetry points
- Added image source telemetry points
> Add `CreateContainerApp` telemetry

- src/commands/secret/deleteSecret/deleteSecret.ts
> Fix hanging `Deleting...` message for `deleteSecret`

- src/commands/image/imageSource/buildImageInAzure/ImageNameStep.ts
> Use root folder name for image name suggestion

- src/utils/pickItem/PickItemOptions.ts
- src/utils/pickItem/pickContainerApp.ts
> Make `skipIfOne` a passable option parameter

- src/utils/treeUtils.ts
Remove since we no longer use this utility
> Remove `findNearestParent` utility

- src/commands/createContainerApp/createContainerApp.ts
- src/commands/createManagedEnvironment/createManagedEnvironment.ts
- src/commands/deployWorkspaceProject/deployWorkspaceProject.ts
- src/commands/image/deployImageApi/deployImage.ts
- src/commands/image/imageSource/buildImageInAzure/ImageNameStep.ts
- src/commands/image/imageSource/containerRegistry/acr/createAcr/createAcr.ts
- src/commands/image/updateImage/updateImage.ts
- src/constants.ts
- src/utils/getVerifyProvidersStep.ts
> Add `Microsoft.ContainerRegistry` provider to the verify providers list

- src/commands/image/imageSource/buildImageInAzure/ImageNameStep.ts
> Improve image name validation & suggestion

- src/commands/image/deployImageApi/deployImage.ts
> Enable admin user when deploying via `deployImageApi`

- src/commands/gitHub/disconnectRepo/disconnectRepo.ts
> Remove loading prompt when disconnecting from a GitHub repository

- package-lock.json
- package.json
- src/commands/createManagedEnvironment/ManagedEnvironmentCreateStep.ts
- src/tree/ManagedEnvironmentItem.ts
Closes #561 
Just handles the short term part of the issue above, will re-open a second issue to address the longer term implementation.
> Enable workload profiles with consumption plan default

- .vscode/settings.json
As per:
https://code.visualstudio.com/updates/v1_83#_code-actions-on-save-and-auto-save
> Update VS Code settings for `codeActionsOnSave`

- src/commands/deployWorkspaceProject/getDeployWorkspaceProjectResults.ts
Old behavior: If a new log analytics workspace was not created, we returned the ID as undefined, even if one was already in use.
New behavior:  Even if a new log analytics workspace was not created, if one is in use, attempt to retrieve its ID.
> Always try to return a log analytics workspace ID when running `deployWorkspaceProject`

- .azure-pipelines/1esmain.yml
- test/global.test.ts
> Add parameter to manually enable long running tests

- src/commands/scaling/scaleRange/ScaleRangePromptStep.ts
> Update scaling range validation to match the portal

- src/commands/createContainerApp/showContainerAppNotification.ts
> Remove potential for duplicate message after creating a container app

- .azure-pipelines/release.yml
See https://github.com/microsoft/vscode-azuretools/pull/1788
> Update release pipeline to pickup new safety improvements

- src/commands/image/imageSource/containerRegistry/acr/AcrListStep.ts
- src/commands/image/imageSource/containerRegistry/acr/AcrRepositoriesListStep.ts
- src/commands/image/imageSource/containerRegistry/dockerHub/DockerHubContainerRepositoryListStep.ts
- src/commands/image/imageSource/containerRegistry/dockerHub/DockerHubNamespaceInputStep.ts
> Fix an issue with currently deployed recommendations

- package.json
> Remove environment variable toggle from command palette

- src/commands/gitHub/connectToGitHub/connectToGitHub.ts
> Update `connectToGitHub` url

- CHANGELOG.md
- NOTICE.html
- package-lock.json
- package.json
@nturinski
Went ahead and drafted the release prep for you.  Feel free to make changes and merge whenever you're ready.  Checklist is also mentioned for reference below.
> v0.8.2 Release Prep

- src/extension.ts
> Register GitHub package extension vars

- src/commands/scaling/scaleRule/deleteScaleRule/DeleteScaleRuleStep.ts
> Fix output log string when deleting a scale rule

- src/commands/ingress/disableIngress/DisableIngressStep.ts
> Small fix and simplify `DisableIngressStep`

- package-lock.json
- package.json
- src/commands/image/imageSource/EnvFileListStep.ts
- src/commands/image/imageSource/containerRegistry/ContainerRegistryListStep.ts
- src/commands/image/imageSource/containerRegistry/RegistryImageInputStep.ts
- src/commands/image/imageSource/containerRegistry/RegistryRepositoriesListBaseStep.ts
- src/commands/image/imageSource/containerRegistry/RepositoryTagListStepBase.ts
- src/commands/image/imageSource/containerRegistry/acr/AcrListStep.ts
- src/commands/image/imageSource/containerRegistry/dockerHub/DockerHubNamespaceInputStep.ts
- src/commands/ingress/IngressPromptStep.ts
- src/commands/ingress/editTargetPort/TargetPortInputStep.ts
- src/commands/ingress/enableIngress/IngressVisibilityStep.ts
- src/commands/registryCredentials/RegistryCredentialsAddConfigurationListStep.ts
- src/webviews/OpenConfirmationViewStep.ts
- src/webviews/confirmationViewController.ts
I need these in order for all of Megan's code to build in order to get the tests to work.
> Implement utils changes

- .vscode/extensions.json
- package-lock.json
- package.json
- src/vscode.proposed.authLearnMore.d.ts
- src/vscode.proposed.authenticationChallenges.d.ts
- test/runTest.ts
There were a lot of changes to Deploy from workspace so I'm making a release branch from v0.9.0 and cherry-picking over the changes that we need for MFA.
> Cherrypick changes for MFA

- test/testProjects/advanced-js/src/package-lock.json
- test/testProjects/advanced-js/src/package.json
- test/testProjects/basic-js/src/package-lock.json
- test/testProjects/basic-js/src/package.json
Dependabot isn't resolving the merge conflicts, it's easy enough to just upgrade the versions myself.
> Bump axios version for test projects

- README.md
Addresses a privacy task that we received
> Update Privacy Statement link
